### ISSUE TITLE
Can not install `aiortc` via pip

### ISSUE THREAD

**Issue by lumenier1** [jlaine/aiortc#107]
Trying to install **aiortc** with pip but an error occurs:

`$ pip3.7 install aiortc `

    ... blah blah blah ...
    copying av/audio/__init__.py -> build/lib.linux-x86_64-3.7/av/audio
        running build_ext
        running config
        Could not find libswscale with pkg-config.
        Could not find libswresample with pkg-config.
    
        ----------------------------------------
    Command "/usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ovjqlmib/av/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ps7tysrf/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ovjqlmib/av/

I've already installed `apt install libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config` packages and the [latest Python v3.7.1.](https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/) also updated pip to v18.1

Using Ubuntu 14.04 LTS Trusty x86_64

**Comment by jlaine** [comment]
This is not due to the install of `aiortc` itself but rather `PyAV`, which requires FFmpeg > 3.2.

On modern Debian/Ubuntu versions, `libswscale-dev` and `libswresample-dev` are pulled in by `libavfilter-dev`, satisfying all required dependencies.  On Ubuntu 14.04, the FFmpeg version is just too old and won't work.
