### ISSUE TITLE
how to write tracks to file?

### ISSUE THREAD

**Issue by JRafiei** [jlaine/aiortc#15]
I want to to write audio tracks in a file, for example a wav file. Could you please provide some information on how to do that?
To be specific, in the examples /server package and in the consume_audio file, how can I write the result of track.recv to a wav file?

**Comment by jlaine** [comment]
I have modified the "server" example to illustrate how to write to a WAV file.

Could you give it a try and let me know if the quality issues remain? If so, can you please describe your setup (what kind of network is there between the two parties). 

On the loopback interface the audio should be perfect. On a network with jitter / packet loss, poor audio quality would be due to the fact aiortc currently doesn't use a jitter buffer for audio reception.

**Comment by JRafiei** [comment]
Thank you jlane! I tested it and everything seems to work fine.

**Comment by jlaine** [comment]
Awesome, in that case your problem was probably that something in the wav header did not match what was actually being written (sample size or rate possibly)
