### ISSUE TITLE
SyntaxError: 'await' expressions in comprehensions are not supported

### ISSUE THREAD

**Issue by mdmelo** [jlaine/aiortc#31]
Hi. I am using Python 3.5.3 on Debian9 and latest aiortc source. I can run the apprtc example fine, but when I attempt to run videostream-cli I get the following error:

mike@debian9:/files/webrtc/aiortc/examples/videostream-cli$ python3 cli.py offer -v
  File "cli.py", line 47
    frames = [await track.recv() for track in self.tracks]
             ^
SyntaxError: 'await' expressions in comprehensions are not supported

Any ideas what I am doing wrong?  Thanks for the excellent webrtc framework!

Mike M.

**Comment by jlaine** [comment]
Ah, I hadn't run that example on Python 3.5 i'll rewrite that line in a more compatible way. Could you check the other examples please and report whether they work?

**Comment by mdmelo** [comment]
OK thanks - apprtc worked just fine just BTW.  I'll test the remaining examples.

I realize 3.5 is a bit out of date, I can build and altinstall 3.7 too.

**Comment by jlaine** [comment]
Python 3.5 is definitely in scope for aiortc, as a lot of stable Linux distros rely on it.

The full codebase of the library is tested against 3.5, 3.6 and 3.7, it's just the examples I cannot autotest as they require human interaction.

aiortc 0.8.0 (released this weekend) contains the fix for the videostream-cli example.

**Comment by mdmelo** [comment]
thanks so much!  will git-pull and give it a try

**Comment by mdmelo** [comment]
works fine with Py 3.5!  server example also works as advertised, just FYI.
