### ISSUE TITLE
LAN-only testing

### ISSUE THREAD

**Issue by nickaknudson** [jlaine/aiortc#51]
I'm trying to do some testing to force all traffic over the LAN. Can you suggest some methods to test this?

I started by filtering all ICE candidates that aren't on the local network. I think that this will ensure a LAN connection, but maybe there is still always the fallback to a TURN server??

To check that it couldn't possibly be using a TURN server, I tried disconnecting the LAN from an internet connection to prove to myself that nothing could be going over the internet, but the ICE gathering process doesn't complete. 

Is there a way to gather ICE candidates without an internet connection? Is there a way to ensure communication is only over LAN?

Thanks.

**Comment by jlaine** [comment]
Unless you explicitly configured a TURN server yourself, none will be used. I'm not sure what you mean by "filtering LAN candidates" as aiortc provides no API for this.

As for ICE not completing when you disconnect internet that is almost certainly because the default config uses a STUN server (Google's). You can change this by passing an RTCConfiguration with iceServers=[] to the RTCPeerConnection constructor.

**Comment by jlaine** [comment]
Finally: to debug where network traffic is going I suggest using Wireshark
