### ISSUE TITLE
happening delay during the call

### ISSUE THREAD

**Issue by mbutler-79** [jlaine/aiortc#64]
Hi jlaine, 
After the call is started between two clients, video of remote client is destroyed and the delay increases (both for audio and video of remote peer) as is shown below :
 
![screencapture-01](https://user-images.githubusercontent.com/43107108/45262517-6c66bb00-b42d-11e8-9f4e-24cbe823230e.png)

Could you tell me how to fix this issue? how can i prevent this problem? related to rtcrtpreceiver.py file and capacity of JitterBuffer?

**Comment by mbutler-79** [comment]
I`ve written a script similar to server.py in example folder, I save media streams of two sides in RAM (by defining list variable for each client), while popping media stream from them, the size of those list variables decreases.
do you think this action is OK? for my case, do you recommend I use ORTC or WebRTC not aiortc ? 
could you please guide me which option is correct?

**Comment by mbutler-79** [comment]
Yep, I mean two sides can be browsers on mobile phones or desktop. I have no processing on their media streams, so maybe it`s better to not use aiortc package as you said.
OK, thanks a lot for your help

**Comment by mbutler-79** [comment]
If I wanted to do any processing on video tracks, you recommend to use aiortc?
could you please tell me use cases of this package?

**Comment by jlaine** [comment]
If you want to process the media, absolutely do use aiortc. I'm just pointing out that to transmit unmodified media it's a shame to introduce an extra hop.

Back to you initial problem: unless you post some code I'm going to have trouble helping you.

**Comment by mbutler-79** [comment]
Thank you so much jlaine 
There is possible to send my code to your email ? (If this email is OK, jeremy.laine@m4x.org)
I`ll try to say enough explaination about it, so you can better find my mistake.
Any problem?

**Comment by jlaine** [comment]
Can you reduce the code to the minimum required to demonstrate the issue and link to a gist please? Email won't help if someone else encounters the same problem in the future, let's keep this out in the open.

**Comment by mbutler-79** [comment]
sorry for answer late, I created a gist and tried to write minimal code as you wanted, I`m so thankfull for helping me:
https://gist.github.com/mbutler-79/e2028cb22fbf9139c7c87736b3d67822

**Comment by fidelcode** [comment]
@jlaine

As long as I understand, what they are going to do is to use 'aiortc' to make the following scenario possible:

Two clients using browsers and not having public IP addresses (behind NAT) communicate with each other through aiortc on a server. So the server starts separate RTC sessions with both of them and transmit video and audio streams from one side to another. One sides' frames remain in the RAM until the other part pulls it off.

There are two things I really do not understand. It would be great if you help me (and mbutler-79) to get on the right track. 

1-Why is it weird for you to create a call in this way while the clients cannot see each others in the network directly. Is there a better way for the same scenario?

2-I read the gist. A separate process is being launched for a call and tries to do all the stuff in it.
It gets streams (audio+video) from one side and put it in a global variable, when the other party asks for a frame it shifts a frame and hands it over.

As long as I understood, There is another async task in the event loop to check if both parties are actively sending frames. If a party does not send a frame for more than 20 seconds, sessions would be terminated for both sides. I have doubts about this task. I guess it makes delay. The event loop has three things to do:

1-It gets frames from a party and push it in a global variable so the other party can shift it.
2-Shift frames and hand them over whenever the other party asks for a new frame.
3-Check if both parties are sending frames.

We all know that a video call is a real time communication (it means peers are sending and receiving frames simultaneously). Assuming that doing things asynchronously in python means we do one and just one thing at a moment, I think the problem is that they need two threads for each call. So all of the jobs for each side being done separately from the other. So, a thread for each side gets the frames and put them in a file and read the other sides file whenever the client asks for a new thread from the other side. What do you think? Am I wrong?

**Comment by fidelcode** [comment]
Just for the record, there is an open source project : https://github.com/twilio
Which does the exact same thing. It uses RTC for voice and video calls and the core is written in python (Sure it does not use aiortc as it started many years before).

**Comment by mbutler-79** [comment]
@fidelcode , yep, this is almost the same work I do. but one point is that there is one separate thread for every conversation between two parties/peers not one thread for every user.
thanks for mentioning  https://github.com/twilio, try to test it, but I think aiortc is more complete than twilio, It has inspired from WebRTC + ORTC.

**Comment by jlaine** [comment]
@fidelcode clients behind a NAT is pretty much the usual situation, this is why STUN and TURN support are baked into WebRTC. Introducing an intermediate server which has to run a full RTP stack and decode/encode the traffic both ways is not the most efficient solution.

**Comment by jlaine** [comment]
@mbutler-79 from what I can tell the part of your code which relays the frames from one party to the other is doing something like a "while" loop interspersed with asyncio.sleep() calls. Why not use an asyncio.Queue instead of polling? You'll probably also want to limit the queue size and drop frames if you fall behind.

Anyway if the only purpose is to relay traffic, you'd be better served by just deploying a TURN server as mentioned above. That way the two parties perform their negotiation directly, and have true end-to-end statistics on how the media is flowing.

**Comment by mbutler-79** [comment]
@jlaine I appreciate for your help
